version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    versioning-strategy: increase
    allow:
      - dependency-type: direct
    labels:
      - "build"
    groups:
      dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 2
    target-branch: "main"
    labels:
      - "build"
