version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: increase
    allow:
      - dependency-type: direct
    labels:
      - "build"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 2
    target-branch: "main"
    labels:
      - "build"
