language: node_js
node_js:
  - "10"
cache: yarn
jobs:
  include:
    - stage: Test
      script: yarn test:lint
    - before_script: yarn global add codecov
      script: yarn test:ci
      after_success: codecov
    - script: yarn test:integration
