language: node_js

cache: yarn

jobs:
  include:
  - stage: test
    env:
    - NAME=yarn
    node_js: "10"
    before_script: yarn global add codecov
    script: yarn test
    after_success: codecov
